version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - revive
    - tparallel
    - unconvert
    - usestdlibvars
    - whitespace

  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: ${base-path}/tools/rules.go
        underef:
          skipRecvDeref: false
    gomoddirectives:
      replace-allow-list:
        - gitlab.com/gitlab-org/api/client-go
      replace-local: true
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - forbidigo
        - tracecheck
        - gomnd
        - gochecknoinits
        - makezero
    revive:
      severity: error
      rules:
        - name: atomic
        - name: line-length-limit
          arguments:
            - 200
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
            - fmt.Fprint
            - fmt.Fprintf
            - fmt.Fprintln
            - os.Stderr.Sync
            - sb.WriteString
            - buf.WriteString
            - hasher.Write
            - os.Setenv
            - os.RemoveAll
        - name: var-naming
          arguments:
            - - ID
              - URL
              - HTTP
              - API
            - []

issues:
  max-same-issues: 50

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
